"""
delivery_stride.py  (converted from: delivery stride metrics.py)

✅ Requirement covered:
- Delivery Stride Duration and Length (BFC → FFC)
- Uses cached keypoints from: <out_dir>/<trial_id>/keypoints.csv  (generated by step_duration.py)
- Outputs (contract with run_all.py):
  1) <out_dir>/<trial_id>/<metric_name>_frames.csv
  2) <out_dir>/<trial_id>/<metric_name>_summary.json
  3) <out_dir>/<trial_id>/<metric_name>_annotated.mp4

✅ Improvements:
- No interactive input() for bowling hand (uses --bowling_arm)
- No repeated YOLO inference (loads cached keypoints.csv)
- Calibration (stump top/bottom clicks) is cached per trial:
    <out_dir>/<trial_id>/calibration.json
  so you click once, then all later scripts can reuse cm_per_pixel/m_per_pixel.

✅ Notes:
- We keep your “velocity-based refined contact” logic, but make it safer:
  - robust peak finding
  - fallbacks if peaks missing
"""

import os
import json
import argparse
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
from scipy.signal import savgol_filter, find_peaks


STUMP_HEIGHT_M = 0.711


# =========================
# UTIL: smoothing window
# =========================
def make_window(n: int, length: int) -> int:
    w = n if n % 2 == 1 else n + 1
    if w >= length:
        w = length - 1 if (length - 1) % 2 == 1 else length - 2
    return max(3, w)

def smooth(sig: np.ndarray, win: int, poly: int) -> np.ndarray:
    if len(sig) < 3:
        return sig.copy()
    w = make_window(win, len(sig))
    return savgol_filter(sig, window_length=w, polyorder=min(poly, w - 1))


# =========================
# UTIL: calibration (cached)
# =========================
def calibrate_pixels_to_m(video_path: Path, calib_path: Path, stump_height_m: float = STUMP_HEIGHT_M):
    """
    Click TOP then BOTTOM of stump on first frame.
    Saves:
      {
        "stump_height_m": 0.711,
        "stump_px": ...,
        "m_per_pixel": ...,
        "cm_per_pixel": ...
      }
    """
    if calib_path.exists():
        with open(calib_path, "r", encoding="utf-8") as f:
            calib = json.load(f)
        # basic validation
        if "m_per_pixel" in calib and "cm_per_pixel" in calib:
            return calib

    cap = cv2.VideoCapture(str(video_path))
    ok, frame = cap.read()
    cap.release()
    if not ok:
        raise RuntimeError("Could not read video for calibration.")

    disp = frame.copy()
    clicks = []

    def on_mouse(event, x, y, flags, param):
        nonlocal disp
        if event == cv2.EVENT_LBUTTONDOWN:
            clicks.append((x, y))

    win_name = "Calibration: click TOP then BOTTOM of stump"
    cv2.namedWindow(win_name, cv2.WINDOW_NORMAL)
    cv2.setMouseCallback(win_name, on_mouse)

    print("\nCALIBRATION:")
    print("Click 1) TOP of stump, then 2) BOTTOM of stump. Press ESC to cancel.")

    while True:
        show = disp.copy()
        for i, (cx, cy) in enumerate(clicks):
            cv2.circle(show, (cx, cy), 6, (0, 255, 0), -1)
            cv2.putText(show, f"{i+1}", (cx + 8, cy - 8),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)

        cv2.putText(show, "Click TOP then BOTTOM of stump (2 clicks). ESC to cancel.",
                    (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2)

        cv2.imshow(win_name, show)
        k = cv2.waitKey(30) & 0xFF
        if k == 27:
            cv2.destroyWindow(win_name)
            raise RuntimeError("Calibration cancelled.")
        if len(clicks) >= 2:
            break

    cv2.destroyWindow(win_name)

    (x1, y1), (x2, y2) = clicks[0], clicks[1]
    stump_px = float(np.hypot(x2 - x1, y2 - y1))
    if stump_px < 2:
        raise RuntimeError("Calibration failed: clicked points too close.")

    m_per_pixel = float(stump_height_m / stump_px)
    cm_per_pixel = float(m_per_pixel * 100.0)

    calib = {
        "stump_height_m": float(stump_height_m),
        "stump_px": stump_px,
        "m_per_pixel": m_per_pixel,
        "cm_per_pixel": cm_per_pixel,
    }

    with open(calib_path, "w", encoding="utf-8") as f:
        json.dump(calib, f, indent=2)

    print(f"✅ Calibration saved: stump_px={stump_px:.2f}px  -> m_per_pixel={m_per_pixel:.6f}, cm_per_pixel={cm_per_pixel:.4f}")
    return calib


# =========================
# CONTACT DETECTION (refined)
# =========================
def find_actual_contact(y_signal: np.ndarray, release_idx: int, fps: float, prefer_last_before=True):
    """
    Finds a peak (max y) and refines backward to first near-zero velocity point.
    y_signal: smoothed ankle y
    prefer_last_before=True -> choose peak closest to release but before it (FFC)
    prefer_last_before=False -> choose peak before given index (BFC)
    """
    n = len(y_signal)
    if n < 5:
        return max(0, min(release_idx, n - 1))

    velocity = np.gradient(y_signal)

    # Peak finding (foot lowest point)
    min_dist = max(3, int(0.10 * fps))  # more conservative than 10 frames
    peaks, _ = find_peaks(y_signal, distance=min_dist)

    if len(peaks) == 0:
        return max(0, min(release_idx, n - 1))

    if prefer_last_before:
        valid = peaks[peaks <= release_idx]
        peak_idx = int(valid[-1]) if len(valid) else int(peaks[-1])
    else:
        valid = peaks[peaks < release_idx]
        peak_idx = int(valid[-1]) if len(valid) else int(peaks[0])

    # Refine: move backward while velocity small (initial contact)
    refined = peak_idx
    v_thresh = 0.5
    back_max = max(5, int(0.15 * fps))  # up to ~150ms

    for i in range(peak_idx, max(-1, peak_idx - back_max), -1):
        if i <= 0:
            break
        if velocity[i] < v_thresh:
            refined = i
        else:
            break

    return int(refined)


# =========================
# MAIN
# =========================
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--video", required=True)
    parser.add_argument("--trial_id", required=True)
    parser.add_argument("--out_dir", required=True)
    parser.add_argument("--view_mode", default="SIDE", choices=["SIDE", "FRONT"])
    parser.add_argument("--bowling_arm", default="RIGHT", choices=["LEFT", "RIGHT"])
    parser.add_argument("--metric_name", default="delivery_stride")

    # tuning
    parser.add_argument("--smooth_window", type=int, default=7)
    parser.add_argument("--smooth_poly", type=int, default=2)
    args = parser.parse_args()

    video_path = Path(args.video)
    out_dir = Path(args.out_dir)
    trial_dir = out_dir / args.trial_id
    trial_dir.mkdir(parents=True, exist_ok=True)

    metric = args.metric_name

    # Inputs expected from step_duration.py
    keypoints_csv = trial_dir / "keypoints.csv"
    step_summary = trial_dir / "step_duration_summary.json"  # to reuse release_frame (optional)

    if not keypoints_csv.exists():
        raise FileNotFoundError(
            f"Missing keypoints.csv in {trial_dir}. "
            f"Run step_duration.py first (or ensure your pipeline runs it first)."
        )

    # Output contract
    frames_out = trial_dir / f"{metric}_frames.csv"
    summary_out = trial_dir / f"{metric}_summary.json"
    annotated_out = trial_dir / f"{metric}_annotated.mp4"
    calib_path = trial_dir / "calibration.json"

    # Read fps from video
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError("Cannot open video")
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()

    print(f"🎥 Frames={total_frames}, FPS={fps:.2f}")

    # Load keypoints
    df = pd.read_csv(keypoints_csv)
    df.ffill(inplace=True)
    df.bfill(inplace=True)

    # Determine bowling wrist based on bowling arm
    bowling_wrist = "right_wrist" if args.bowling_arm.upper() == "RIGHT" else "left_wrist"

    # Release detection:
    # Prefer the step_duration summary release_frame for consistency across scripts
    release_frame = None
    if step_summary.exists():
        with open(step_summary, "r", encoding="utf-8") as f:
            ss = json.load(f)
        release_frame = ss.get("release_frame", None)

    if release_frame is None:
        wrist_y = df[f"{bowling_wrist}_y"].astype(float).to_numpy()
        wrist_y_sm = smooth(wrist_y, args.smooth_window, args.smooth_poly)
        release_idx = int(np.nanargmin(wrist_y_sm))
        release_frame = int(df.loc[release_idx, "frame"])
    else:
        release_idx = int(df.index[df["frame"] == release_frame][0])

    print(f"🏏 Release frame: {int(release_frame)}")

    # Identify front/back foot by bowling arm (common coaching convention):
    # Right-arm bowler -> front foot = left, back foot = right
    # Left-arm bowler  -> front foot = right, back foot = left
    f_side = "left" if args.bowling_arm.upper() == "RIGHT" else "right"
    b_side = "right" if f_side == "left" else "left"

    # Smooth ankle signals
    l_y = df["left_ankle_y"].astype(float).to_numpy()
    r_y = df["right_ankle_y"].astype(float).to_numpy()
    l_sm = smooth(l_y, args.smooth_window, args.smooth_poly)
    r_sm = smooth(r_y, args.smooth_window, args.smooth_poly)

    # pick signals
    f_sm = l_sm if f_side == "left" else r_sm
    b_sm = r_sm if b_side == "right" else l_sm

    # Find refined contacts
    ffc_idx = find_actual_contact(f_sm, release_idx, fps, prefer_last_before=True)
    # BFC should be before FFC -> search using ffc_idx as the "release_idx" boundary
    bfc_idx = find_actual_contact(b_sm, ffc_idx, fps, prefer_last_before=False)

    ffc_frame = int(df.loc[ffc_idx, "frame"])
    bfc_frame = int(df.loc[bfc_idx, "frame"])

    # Coordinates at contacts
    bx = float(df.loc[bfc_idx, f"{b_side}_ankle_x"])
    by = float(df.loc[bfc_idx, f"{b_side}_ankle_y"])
    fx = float(df.loc[ffc_idx, f"{f_side}_ankle_x"])
    fy = float(df.loc[ffc_idx, f"{f_side}_ankle_y"])

    stride_px = float(np.hypot(fx - bx, fy - by))
    stride_duration_s = float((ffc_frame - bfc_frame) / fps) if ffc_frame > bfc_frame else 0.0

    # Calibration (cached)
    calib = calibrate_pixels_to_m(video_path, calib_path, STUMP_HEIGHT_M)
    m_per_pixel = float(calib["m_per_pixel"])
    cm_per_pixel = float(calib["cm_per_pixel"])

    stride_m = float(stride_px * m_per_pixel)

    print("\n🏏 DELIVERY STRIDE METRICS")
    print(f"BFC Frame: {bfc_frame}")
    print(f"FFC Frame: {ffc_frame}")
    print(f"Release Frame: {int(release_frame)}")
    print(f"Stride Length: {stride_m:.3f} m")
    print(f"Stride Duration: {stride_duration_s:.3f} s")

    # -------------------------
    # FRAME-LEVEL OUTPUT (this requirement)
    # -------------------------
    frames_df = pd.DataFrame({
        "frame": df["frame"].astype(int),

        # smoothed ankle signals (useful for plots/debug)
        "left_ankle_y_sm": l_sm.astype(float),
        "right_ankle_y_sm": r_sm.astype(float),

        # event flags
        "is_bfc": 0,
        "is_ffc": 0,
        "is_release": 0,

        # store the chosen sides (constant across frames; duplicated is fine)
        "front_foot": f_side.upper(),
        "back_foot": b_side.upper(),
    })

    frames_df.loc[frames_df["frame"] == bfc_frame, "is_bfc"] = 1
    frames_df.loc[frames_df["frame"] == ffc_frame, "is_ffc"] = 1
    frames_df.loc[frames_df["frame"] == int(release_frame), "is_release"] = 1

    # Put stride info on the FFC frame (NaN elsewhere)
    frames_df["stride_length_px"] = np.nan
    frames_df["stride_length_m"] = np.nan
    frames_df["stride_duration_s"] = np.nan
    frames_df.loc[frames_df["frame"] == ffc_frame, "stride_length_px"] = stride_px
    frames_df.loc[frames_df["frame"] == ffc_frame, "stride_length_m"] = stride_m
    frames_df.loc[frames_df["frame"] == ffc_frame, "stride_duration_s"] = stride_duration_s

    frames_df.to_csv(frames_out, index=False)
    print(f"📌 Saved frames CSV: {frames_out}")

    # -------------------------
    # SUMMARY JSON (trial-level)
    # -------------------------
    summary = {
        "fps": float(fps),
        "cm_per_pixel": float(cm_per_pixel),
        "m_per_pixel": float(m_per_pixel),

        "bowling_arm": args.bowling_arm.upper(),
        "view_mode": args.view_mode.upper(),

        "bfc_frame": int(bfc_frame),
        "ffc_frame": int(ffc_frame),
        "release_frame": int(release_frame),

        "front_foot": f_side.upper(),
        "back_foot": b_side.upper(),

        "stride_length_px": float(stride_px),
        "stride_length_m": float(stride_m),
        "stride_duration_s": float(stride_duration_s),
    }

    with open(summary_out, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    print(f"📌 Saved summary JSON: {summary_out}")

    # -------------------------
    # ANNOTATED VIDEO
    # -------------------------
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        print("⚠️ Could not open video for annotation.")
        return

    out = cv2.VideoWriter(
        str(annotated_out),
        cv2.VideoWriter_fourcc(*"mp4v"),
        float(fps),
        (width, height),
    )

    frame_no = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frame_no += 1

        if frame_no == bfc_frame:
            cv2.circle(frame, (int(bx), int(by)), 18, (0, 0, 255), -1)
            cv2.putText(frame, "BFC", (50, 80), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0, 255), 4)

        if frame_no == ffc_frame:
            cv2.circle(frame, (int(fx), int(fy)), 18, (0, 255, 0), -1)
            cv2.line(frame, (int(bx), int(by)), (int(fx), int(fy)), (255, 255, 255), 3)
            cv2.putText(frame, "FFC", (50, 160), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 255, 0), 4)
            cv2.putText(frame, f"Stride: {stride_m:.2f} m", (50, 230), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 3)

        if frame_no == int(release_frame):
            cv2.putText(frame, "RELEASE", (50, 300), cv2.FONT_HERSHEY_SIMPLEX, 2, (255, 255, 0), 4)

        out.write(frame)

    cap.release()
    out.release()
    print(f"🎥 Annotated video saved: {annotated_out}")


if __name__ == "__main__":
    main()